### ISSUE TITLE
How do I add my own packages, and how do I update the REPO file in the ports/core folder?

### ISSUE THREAD

**Issue by snoglobe** [emmett1/lfs-scripts#23]
I modified the filesystem port to add my own bash PS1 prompt, and I also would like to add my own packages. Does the script auto-install every port inside of the ports folder to the system, or is there a file I have to add the port to, to make the script install it?

**Comment by emmett1** [comment]
You can add your own ports into 'ports/extra' directory. Then add your port into 'PKGS' in 02-base script.

**Comment by snoglobe** [comment]
> You can add your own ports into 'ports/extra' directory. Then add your port into 'PKGS' in 02-base script.

Thank you!
