### ISSUE TITLE
setting sym link error

### ISSUE THREAD

**Issue by hyperclock** [emmett1/lfs-scripts#25]
When starting with ./01-toolchain, I get a message stating:

> please create required '/tools' symlink by running 'ln -svf $PWD//home/hyperclock/lfs-scripts/lfs-rootfs/tools' as root
 
this does not work - this does however:
> ln -svf  /home/hyperclock/lfs-scripts/lfs-rootfs/tools /tools

Could it be that the sym link command is placed wrong? or did I do something wrong.

**Comment by emmett1** [comment]
Ops, maybe error message for symlink is wrong. I will fix it. Thanks for the report.

**Comment by hyperclock** [comment]
tested a few times on various hosts, worked perfectly.

thanx!
